// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClusterMonitorWorkerServiceClient is the client API for ClusterMonitorWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterMonitorWorkerServiceClient interface {
}

type clusterMonitorWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterMonitorWorkerServiceClient(cc grpc.ClientConnInterface) ClusterMonitorWorkerServiceClient {
	return &clusterMonitorWorkerServiceClient{cc}
}

// ClusterMonitorWorkerServiceServer is the server API for ClusterMonitorWorkerService service.
// All implementations must embed UnimplementedClusterMonitorWorkerServiceServer
// for forward compatibility
type ClusterMonitorWorkerServiceServer interface {
	mustEmbedUnimplementedClusterMonitorWorkerServiceServer()
}

// UnimplementedClusterMonitorWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClusterMonitorWorkerServiceServer struct {
}

func (UnimplementedClusterMonitorWorkerServiceServer) mustEmbedUnimplementedClusterMonitorWorkerServiceServer() {
}

// UnsafeClusterMonitorWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterMonitorWorkerServiceServer will
// result in compilation errors.
type UnsafeClusterMonitorWorkerServiceServer interface {
	mustEmbedUnimplementedClusterMonitorWorkerServiceServer()
}

func RegisterClusterMonitorWorkerServiceServer(s grpc.ServiceRegistrar, srv ClusterMonitorWorkerServiceServer) {
	s.RegisterService(&ClusterMonitorWorkerService_ServiceDesc, srv)
}

// ClusterMonitorWorkerService_ServiceDesc is the grpc.ServiceDesc for ClusterMonitorWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterMonitorWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.clutsermonitor.server.v1.ClusterMonitorWorkerService",
	HandlerType: (*ClusterMonitorWorkerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/v1/monitor_server_worker.proto",
}
