// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: api/v1/monitor_server.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListClusterSnapshotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter  *ListClusterSnapshotsRequest_Filter  `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	GroupBy *ListClusterSnapshotsRequest_GroupBy `protobuf:"bytes,2,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
}

func (x *ListClusterSnapshotsRequest) Reset() {
	*x = ListClusterSnapshotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_monitor_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClusterSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterSnapshotsRequest) ProtoMessage() {}

func (x *ListClusterSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_monitor_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListClusterSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_monitor_server_proto_rawDescGZIP(), []int{0}
}

func (x *ListClusterSnapshotsRequest) GetFilter() *ListClusterSnapshotsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListClusterSnapshotsRequest) GetGroupBy() *ListClusterSnapshotsRequest_GroupBy {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

type ListClusterSnapshotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datapoints []*ListClusterSnapshotsResponse_Datapoint `protobuf:"bytes,1,rep,name=datapoints,proto3" json:"datapoints,omitempty"`
}

func (x *ListClusterSnapshotsResponse) Reset() {
	*x = ListClusterSnapshotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_monitor_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClusterSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterSnapshotsResponse) ProtoMessage() {}

func (x *ListClusterSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_monitor_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListClusterSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_monitor_server_proto_rawDescGZIP(), []int{1}
}

func (x *ListClusterSnapshotsResponse) GetDatapoints() []*ListClusterSnapshotsResponse_Datapoint {
	if x != nil {
		return x.Datapoints
	}
	return nil
}

type ListClusterSnapshotsRequest_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListClusterSnapshotsRequest_Filter) Reset() {
	*x = ListClusterSnapshotsRequest_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_monitor_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClusterSnapshotsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterSnapshotsRequest_Filter) ProtoMessage() {}

func (x *ListClusterSnapshotsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_monitor_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterSnapshotsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListClusterSnapshotsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_v1_monitor_server_proto_rawDescGZIP(), []int{0, 0}
}

type ListClusterSnapshotsRequest_GroupBy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListClusterSnapshotsRequest_GroupBy) Reset() {
	*x = ListClusterSnapshotsRequest_GroupBy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_monitor_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClusterSnapshotsRequest_GroupBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterSnapshotsRequest_GroupBy) ProtoMessage() {}

func (x *ListClusterSnapshotsRequest_GroupBy) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_monitor_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterSnapshotsRequest_GroupBy.ProtoReflect.Descriptor instead.
func (*ListClusterSnapshotsRequest_GroupBy) Descriptor() ([]byte, []int) {
	return file_api_v1_monitor_server_proto_rawDescGZIP(), []int{0, 1}
}

type ListClusterSnapshotsResponse_GroupingKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListClusterSnapshotsResponse_GroupingKey) Reset() {
	*x = ListClusterSnapshotsResponse_GroupingKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_monitor_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClusterSnapshotsResponse_GroupingKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterSnapshotsResponse_GroupingKey) ProtoMessage() {}

func (x *ListClusterSnapshotsResponse_GroupingKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_monitor_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterSnapshotsResponse_GroupingKey.ProtoReflect.Descriptor instead.
func (*ListClusterSnapshotsResponse_GroupingKey) Descriptor() ([]byte, []int) {
	return file_api_v1_monitor_server_proto_rawDescGZIP(), []int{1, 0}
}

type ListClusterSnapshotsResponse_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupingKey *ListClusterSnapshotsResponse_GroupingKey `protobuf:"bytes,1,opt,name=grouping_key,json=groupingKey,proto3" json:"grouping_key,omitempty"`
	GpuCapacity int32                                     `protobuf:"varint,2,opt,name=gpu_capacity,json=gpuCapacity,proto3" json:"gpu_capacity,omitempty"`
}

func (x *ListClusterSnapshotsResponse_Value) Reset() {
	*x = ListClusterSnapshotsResponse_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_monitor_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClusterSnapshotsResponse_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterSnapshotsResponse_Value) ProtoMessage() {}

func (x *ListClusterSnapshotsResponse_Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_monitor_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterSnapshotsResponse_Value.ProtoReflect.Descriptor instead.
func (*ListClusterSnapshotsResponse_Value) Descriptor() ([]byte, []int) {
	return file_api_v1_monitor_server_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListClusterSnapshotsResponse_Value) GetGroupingKey() *ListClusterSnapshotsResponse_GroupingKey {
	if x != nil {
		return x.GroupingKey
	}
	return nil
}

func (x *ListClusterSnapshotsResponse_Value) GetGpuCapacity() int32 {
	if x != nil {
		return x.GpuCapacity
	}
	return 0
}

type ListClusterSnapshotsResponse_Datapoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// timesecond is the Unix timestamp in seconds.
	Timestamp int64                                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Values    []*ListClusterSnapshotsResponse_Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ListClusterSnapshotsResponse_Datapoint) Reset() {
	*x = ListClusterSnapshotsResponse_Datapoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_monitor_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClusterSnapshotsResponse_Datapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterSnapshotsResponse_Datapoint) ProtoMessage() {}

func (x *ListClusterSnapshotsResponse_Datapoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_monitor_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterSnapshotsResponse_Datapoint.ProtoReflect.Descriptor instead.
func (*ListClusterSnapshotsResponse_Datapoint) Descriptor() ([]byte, []int) {
	return file_api_v1_monitor_server_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ListClusterSnapshotsResponse_Datapoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ListClusterSnapshotsResponse_Datapoint) GetValues() []*ListClusterSnapshotsResponse_Value {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_api_v1_monitor_server_proto protoreflect.FileDescriptor

var file_api_v1_monitor_server_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x6c,
	0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xf6, 0x01, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x5e, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x46, 0x2e, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x62, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x47, 0x2e, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x42, 0x79, 0x1a, 0x08, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x09, 0x0a,
	0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x22, 0xc3, 0x03, 0x0a, 0x1c, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x0a, 0x64, 0x61, 0x74,
	0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x4a, 0x2e,
	0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x0d, 0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e,
	0x67, 0x4b, 0x65, 0x79, 0x1a, 0x9b, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x6f,
	0x0a, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72,
	0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x4b,
	0x65, 0x79, 0x52, 0x0b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x12,
	0x21, 0x0a, 0x0c, 0x67, 0x70, 0x75, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x67, 0x70, 0x75, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x1a, 0x89, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x5e,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46,
	0x2e, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x32, 0xe2,
	0x01, 0x0a, 0x15, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0xc8, 0x01, 0x0a, 0x14, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x73, 0x12, 0x3f, 0x2e, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x40, 0x2e, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x27, 0x12, 0x25, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_monitor_server_proto_rawDescOnce sync.Once
	file_api_v1_monitor_server_proto_rawDescData = file_api_v1_monitor_server_proto_rawDesc
)

func file_api_v1_monitor_server_proto_rawDescGZIP() []byte {
	file_api_v1_monitor_server_proto_rawDescOnce.Do(func() {
		file_api_v1_monitor_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_monitor_server_proto_rawDescData)
	})
	return file_api_v1_monitor_server_proto_rawDescData
}

var file_api_v1_monitor_server_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_monitor_server_proto_goTypes = []interface{}{
	(*ListClusterSnapshotsRequest)(nil),              // 0: llmariner.clustermonitor.server.v1.ListClusterSnapshotsRequest
	(*ListClusterSnapshotsResponse)(nil),             // 1: llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse
	(*ListClusterSnapshotsRequest_Filter)(nil),       // 2: llmariner.clustermonitor.server.v1.ListClusterSnapshotsRequest.Filter
	(*ListClusterSnapshotsRequest_GroupBy)(nil),      // 3: llmariner.clustermonitor.server.v1.ListClusterSnapshotsRequest.GroupBy
	(*ListClusterSnapshotsResponse_GroupingKey)(nil), // 4: llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse.GroupingKey
	(*ListClusterSnapshotsResponse_Value)(nil),       // 5: llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse.Value
	(*ListClusterSnapshotsResponse_Datapoint)(nil),   // 6: llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse.Datapoint
}
var file_api_v1_monitor_server_proto_depIdxs = []int32{
	2, // 0: llmariner.clustermonitor.server.v1.ListClusterSnapshotsRequest.filter:type_name -> llmariner.clustermonitor.server.v1.ListClusterSnapshotsRequest.Filter
	3, // 1: llmariner.clustermonitor.server.v1.ListClusterSnapshotsRequest.group_by:type_name -> llmariner.clustermonitor.server.v1.ListClusterSnapshotsRequest.GroupBy
	6, // 2: llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse.datapoints:type_name -> llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse.Datapoint
	4, // 3: llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse.Value.grouping_key:type_name -> llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse.GroupingKey
	5, // 4: llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse.Datapoint.values:type_name -> llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse.Value
	0, // 5: llmariner.clustermonitor.server.v1.ClusterMonitorService.ListClusterSnapshots:input_type -> llmariner.clustermonitor.server.v1.ListClusterSnapshotsRequest
	1, // 6: llmariner.clustermonitor.server.v1.ClusterMonitorService.ListClusterSnapshots:output_type -> llmariner.clustermonitor.server.v1.ListClusterSnapshotsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_monitor_server_proto_init() }
func file_api_v1_monitor_server_proto_init() {
	if File_api_v1_monitor_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_monitor_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClusterSnapshotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_monitor_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClusterSnapshotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_monitor_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClusterSnapshotsRequest_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_monitor_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClusterSnapshotsRequest_GroupBy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_monitor_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClusterSnapshotsResponse_GroupingKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_monitor_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClusterSnapshotsResponse_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_monitor_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClusterSnapshotsResponse_Datapoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_monitor_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_monitor_server_proto_goTypes,
		DependencyIndexes: file_api_v1_monitor_server_proto_depIdxs,
		MessageInfos:      file_api_v1_monitor_server_proto_msgTypes,
	}.Build()
	File_api_v1_monitor_server_proto = out.File
	file_api_v1_monitor_server_proto_rawDesc = nil
	file_api_v1_monitor_server_proto_goTypes = nil
	file_api_v1_monitor_server_proto_depIdxs = nil
}
