// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClusterMonitorWorkerServiceClient is the client API for ClusterMonitorWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterMonitorWorkerServiceClient interface {
	SendClusterTelemetry(ctx context.Context, in *SendClusterTelemetryRequest, opts ...grpc.CallOption) (*SendClusterTelemetryResponse, error)
}

type clusterMonitorWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterMonitorWorkerServiceClient(cc grpc.ClientConnInterface) ClusterMonitorWorkerServiceClient {
	return &clusterMonitorWorkerServiceClient{cc}
}

func (c *clusterMonitorWorkerServiceClient) SendClusterTelemetry(ctx context.Context, in *SendClusterTelemetryRequest, opts ...grpc.CallOption) (*SendClusterTelemetryResponse, error) {
	out := new(SendClusterTelemetryResponse)
	err := c.cc.Invoke(ctx, "/llmariner.clustermonitor.server.v1.ClusterMonitorWorkerService/SendClusterTelemetry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterMonitorWorkerServiceServer is the server API for ClusterMonitorWorkerService service.
// All implementations must embed UnimplementedClusterMonitorWorkerServiceServer
// for forward compatibility
type ClusterMonitorWorkerServiceServer interface {
	SendClusterTelemetry(context.Context, *SendClusterTelemetryRequest) (*SendClusterTelemetryResponse, error)
	mustEmbedUnimplementedClusterMonitorWorkerServiceServer()
}

// UnimplementedClusterMonitorWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClusterMonitorWorkerServiceServer struct {
}

func (UnimplementedClusterMonitorWorkerServiceServer) SendClusterTelemetry(context.Context, *SendClusterTelemetryRequest) (*SendClusterTelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendClusterTelemetry not implemented")
}
func (UnimplementedClusterMonitorWorkerServiceServer) mustEmbedUnimplementedClusterMonitorWorkerServiceServer() {
}

// UnsafeClusterMonitorWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterMonitorWorkerServiceServer will
// result in compilation errors.
type UnsafeClusterMonitorWorkerServiceServer interface {
	mustEmbedUnimplementedClusterMonitorWorkerServiceServer()
}

func RegisterClusterMonitorWorkerServiceServer(s grpc.ServiceRegistrar, srv ClusterMonitorWorkerServiceServer) {
	s.RegisterService(&ClusterMonitorWorkerService_ServiceDesc, srv)
}

func _ClusterMonitorWorkerService_SendClusterTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendClusterTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterMonitorWorkerServiceServer).SendClusterTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.clustermonitor.server.v1.ClusterMonitorWorkerService/SendClusterTelemetry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterMonitorWorkerServiceServer).SendClusterTelemetry(ctx, req.(*SendClusterTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterMonitorWorkerService_ServiceDesc is the grpc.ServiceDesc for ClusterMonitorWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterMonitorWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.clustermonitor.server.v1.ClusterMonitorWorkerService",
	HandlerType: (*ClusterMonitorWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendClusterTelemetry",
			Handler:    _ClusterMonitorWorkerService_SendClusterTelemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/monitor_server_worker.proto",
}
